name: test

on: [push, pull_request]

# Cancel running jobs for the same workflow and branch.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false

      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
        qt-lib: [pyqt5, pyqt6, pyside2, pyside6]
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - python-version: "3.7"
            tox-env: "py37"
          - python-version: "3.8"
            tox-env: "py38"
          - python-version: "3.9"
            tox-env: "py39"
          - python-version: "3.10"
            tox-env: "py310"
          - python-version: "3.11"
            tox-env: "py311"
        exclude:
          # Not installable:
          # ERROR: Could not find a version that satisfies the requirement pyside2 (from versions: none)
          - python-version: "3.11"
            qt-lib: pyside2
            os: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox
        if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
          sudo apt-get update -y
          sudo apt-get install -y libgles2-mesa-dev
        fi
      shell: bash
    - name: Test with tox
      run: |
        tox -e ${{ matrix.tox-env }}-${{ matrix.qt-lib }} -- -ra --color=yes
